version: "3"

services:

  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: elasticsearch
    mem_limit: 8G
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"

  kibana:
    image: kibana:8.4.0 # http://localhost:5601
    container_name: kibana
    ports:
      - "5601:5601"

volumes:
  elastic: { }